### ISSUE TITLE
Works with G935

### ISSUE THREAD

**Issue by Hipperooni** [andyvorld/LGSTrayBattery_GHUB#1]
Sorry, dont use GitHub much so dont know if this is the right place for this, but can confirm this works perfectly with my G935 headset! Would be nice if there was a way to change the icon to a headset instead of the mouse icon though. This program is awesome.

**Comment by andyvorld** [comment]
I just reworked my other program to fold in the GHUB layer as well as the reactive icons, [here](https://github.com/andyvorld/LGSTrayBattery/releases/tag/v2.0.0_alpha). 
It is currently in alpha, which means it is not completely on feature parity with the existing stuff, but from now onwards it will be quite likely I am going to archive LGSTrayBattery_GHUB in favor of the new LGSTrayBattery.
