### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by sburke781** [andyvorld/LGSTrayBattery_GHUB#2]
I was hoping to use this app to access the battery levels of my mouse and keyboard from my home automation hub (Hubitat).  I can't seen to get it to access the devices page to get the listing.  I have tried opening up the port being used through the Windows Firewall policies, but still cannot get it to work.  Localhost calls work locally on the host laptop, but not from outside, or even by using the IP address in a local browser.

Any thoughts / tips?

**Comment by andyvorld** [comment]
Am I correct in asssuming your use case is the following,
- M/KB attached to laptop
- Laptop using LGSTrasyBattery with Webserver turned on
- Hubitat trying to reach laptop:12321/devices

If that is the case, the program is defaulted to binding only to localhost, meaning it can only be accessed by the host.

I can have a thinker with it to allow you to do abitrary bindings, as from earlier experimentation binding to the interface IP address (accessable from outside the host) requires admin permissions.

**Comment by sburke781** [comment]
That's correct in terms of the use case you described.

So a simple method for testing would be issuing a HTTP Get from a second computer using something like Postman or curl, for example, requesting the list of devices and then the battery levels on another PC / laptop.

If you could look at this, that would be great, but no rush...

**Comment by sburke781** [comment]
Thinking about it some more, I'd also be happy to look at options for managing the external access through something like IIS, with a page to call the app you have developed.

**Comment by andyvorld** [comment]
I just pushed an [update](https://github.com/andyvorld/LGSTrayBattery/releases/tag/v1.0.10), you will need to run it once to generate the fields in the `HttpConfig.ini`, and update `tcpAddr` to `0.0.0.0` or your target IP for binding, before restarting the program.

**Comment by sburke781** [comment]
Wow, wasn't expecting such a quick turnaround, thanks for that.  I'll check out later tonight and let you know if it works for me.

**Comment by sburke781** [comment]
Any chance you could make this change under the G-Hub version?

Thanks,
Simon

**Comment by andyvorld** [comment]
I just updated it here https://github.com/andyvorld/LGSTrayBattery_GHUB/releases/tag/v0.4,

I'm starting to think I should probably merge the two projects togather, as there are quite a lot of duplicate code.

**Comment by sburke781** [comment]
I assume I was meant to replace localhost with my IP address in the ini file?  I tried that, exited and restarted the app and still got an error, even accessing from a local browser, e.g.:

http://192.168.0.44:12321/devices

Thanks again for the quick response.

**Comment by sburke781** [comment]
I take that back, it worked!!

**Comment by sburke781** [comment]
I can call it from another "PC" (raspberry PI), so it must be something in my call from my Hubitat.  I'll stop spamming the comments here.  I believe it works, I just need to look at my code on my hub.

Simon

**Comment by andyvorld** [comment]
To be honest it can just be that I am using a non-standard way of sending the HTTP packets, as it was "hand-crafted" without using a proper library as it was an after thought to get it working with rainmeter.

**Comment by andyvorld** [comment]
I had a look at my code, it does seem I was sending some invalid headers.
Ill push an update soon.

**Comment by andyvorld** [comment]
Try this version, https://github.com/andyvorld/LGSTrayBattery_GHUB/releases/tag/v0.4.1

**Comment by sburke781** [comment]
For now I'm going to say success, need to tweak my code (I expect) to parse the html in more detail, but am not seeing the error I was seeing earlier.  If we can leave the issue open for another day or two I can test that part in more detail.

Thanks again,
Simon

**Comment by sburke781** [comment]
Yep, happy to say that is successful, can see the html come through.  May be easier with a json or xml output option, but am happy to play with it some more myself for now.

Also happy to close this issue.
